### ISSUE TITLE
Add option to scan specific user

### ISSUE THREAD

**Issue by dtnml** [lc/secretz#3]
Great tool BTW..👍👍👏

Adding the option to scan a specific github org user/member shall be helpful to avoid being rate-limited by the api.

Last thing ....._could you briefly explain what the "-c" flag does._

**Comment by lc** [comment]
Hi,

You can already scan a specific Github member by just specifying their username in the `-t` flag rather than specifying the organization.

For example, this command will get my TravisCI build logs:

`secretz -t lc -delay 1000 -c 1 `

Also, the `-c` flag limits the number of workers that are spawned by the tool. The higher the value of the `-c` flag, the faster it will retrieve and save logs from TravisCI. Lower values are better as it'll keep you from being rate-limited.
